# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1487/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1487/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/Redmi/OneDrive/Рабочий стол/lr3e"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/Redmi/OneDrive/Рабочий стол/lr3e"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1487/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1487/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/Redmi/OneDrive/Рабочий стол/lr3e/CMakeFiles" "/mnt/c/Users/Redmi/OneDrive/Рабочий стол/lr3e//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/Redmi/OneDrive/Рабочий стол/lr3e/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named figures_main

# Build rule for target.
figures_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figures_main
.PHONY : figures_main

# fast build rule for target.
figures_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/build
.PHONY : figures_main/fast

#=============================================================================
# Target rules for targets named figures_tests

# Build rule for target.
figures_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figures_tests
.PHONY : figures_tests

# fast build rule for target.
figures_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/build
.PHONY : figures_tests/fast

figure.o: figure.cpp.o
.PHONY : figure.o

# target to build an object file
figure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/figure.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/figure.cpp.o
.PHONY : figure.cpp.o

figure.i: figure.cpp.i
.PHONY : figure.i

# target to preprocess a source file
figure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/figure.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/figure.cpp.i
.PHONY : figure.cpp.i

figure.s: figure.cpp.s
.PHONY : figure.s

# target to generate assembly for a file
figure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/figure.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/figure.cpp.s
.PHONY : figure.cpp.s

figure_array.o: figure_array.cpp.o
.PHONY : figure_array.o

# target to build an object file
figure_array.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/figure_array.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/figure_array.cpp.o
.PHONY : figure_array.cpp.o

figure_array.i: figure_array.cpp.i
.PHONY : figure_array.i

# target to preprocess a source file
figure_array.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/figure_array.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/figure_array.cpp.i
.PHONY : figure_array.cpp.i

figure_array.s: figure_array.cpp.s
.PHONY : figure_array.s

# target to generate assembly for a file
figure_array.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/figure_array.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/figure_array.cpp.s
.PHONY : figure_array.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/main.cpp.s
.PHONY : main.cpp.s

octagon.o: octagon.cpp.o
.PHONY : octagon.o

# target to build an object file
octagon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/octagon.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/octagon.cpp.o
.PHONY : octagon.cpp.o

octagon.i: octagon.cpp.i
.PHONY : octagon.i

# target to preprocess a source file
octagon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/octagon.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/octagon.cpp.i
.PHONY : octagon.cpp.i

octagon.s: octagon.cpp.s
.PHONY : octagon.s

# target to generate assembly for a file
octagon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/octagon.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/octagon.cpp.s
.PHONY : octagon.cpp.s

square.o: square.cpp.o
.PHONY : square.o

# target to build an object file
square.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/square.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/square.cpp.o
.PHONY : square.cpp.o

square.i: square.cpp.i
.PHONY : square.i

# target to preprocess a source file
square.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/square.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/square.cpp.i
.PHONY : square.cpp.i

square.s: square.cpp.s
.PHONY : square.s

# target to generate assembly for a file
square.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/square.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/square.cpp.s
.PHONY : square.cpp.s

tests.o: tests.cpp.o
.PHONY : tests.o

# target to build an object file
tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/tests.cpp.o
.PHONY : tests.cpp.o

tests.i: tests.cpp.i
.PHONY : tests.i

# target to preprocess a source file
tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/tests.cpp.i
.PHONY : tests.cpp.i

tests.s: tests.cpp.s
.PHONY : tests.s

# target to generate assembly for a file
tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/tests.cpp.s
.PHONY : tests.cpp.s

triangle.o: triangle.cpp.o
.PHONY : triangle.o

# target to build an object file
triangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/triangle.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/triangle.cpp.o
.PHONY : triangle.cpp.o

triangle.i: triangle.cpp.i
.PHONY : triangle.i

# target to preprocess a source file
triangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/triangle.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/triangle.cpp.i
.PHONY : triangle.cpp.i

triangle.s: triangle.cpp.s
.PHONY : triangle.s

# target to generate assembly for a file
triangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_main.dir/build.make CMakeFiles/figures_main.dir/triangle.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figures_tests.dir/build.make CMakeFiles/figures_tests.dir/triangle.cpp.s
.PHONY : triangle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... figures_main"
	@echo "... figures_tests"
	@echo "... figure.o"
	@echo "... figure.i"
	@echo "... figure.s"
	@echo "... figure_array.o"
	@echo "... figure_array.i"
	@echo "... figure_array.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... octagon.o"
	@echo "... octagon.i"
	@echo "... octagon.s"
	@echo "... square.o"
	@echo "... square.i"
	@echo "... square.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
	@echo "... triangle.o"
	@echo "... triangle.i"
	@echo "... triangle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

